@Library('jenkins-pipeline-utils') _

node('preint'){
  properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')),
    [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false],
    parameters([
      string(defaultValue: 'latest', description: 'Intake container version', name: 'APP_VERSION'),
      string(defaultValue: 'inventories/preint/hosts.yml', description: 'Ansible inventory', name: 'INVENTORY'),
      string(defaultValue: 'deploy-intake.yml', description: 'Ansible playbook', name: 'PLAYBOOK_NAME'),
      booleanParam(defaultValue: true, description: 'Enable/Disable New Relic agent', name: 'ENABLE_NEWRELIC')]),pipelineTriggers([])
  ])

  stage('Get necessary artifacts'){
    git branch: 'master', credentialsId: '433ac100-b3c2-4519-b4d6-207c029a103b', url: 'git@github.com:ca-cwds/devops.git'
    dir('de-ansible'){
      git branch: 'master', credentialsId: '433ac100-b3c2-4519-b4d6-207c029a103b', url: 'git@github.com:ca-cwds/de-ansible.git'
    }
  }

  stage('Deploy to preint'){
    dir('de-ansible'){
      sh "ansible-playbook -e NEW_RELIC_AGENT=$ENABLE_NEWRELIC -e INTAKE_APP_VERSION=$APP_VERSION -i $INVENTORY $PLAYBOOK_NAME --vault-password-file ~/.ssh/vault.txt -vv"
    }
  }

  stage('Update manifest'){
    updateManifest("intake", "preint", "433ac100-b3c2-4519-b4d6-207c029a103b", env.APP_VERSION)
  }

  stage ('Trigger Smoke acceptance tests') {
           build job: '/Acceptance_tests/acceptance-test-intake/',
               parameters: [string(name: 'INTAKE_APP_VERSION', value: env.APP_VERSION)],
               wait: false
  }

  stage('Clean'){
    cleanWs()
  }
}
