node('preint'){
  properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')),
    [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false],
    parameters([
      string(defaultValue: 'latest', description: 'Intake container version', name: 'INTAKE_APP_VERSION'),
      booleanParam(defaultValue: true, description: 'Enable/Disable New Relic agent', name: 'ENABLE_NEWRELIC')]),pipelineTriggers([])
  ])

  stage('Get deploy utils'){
    git branch: 'FIT-48-create-a-pipeline-for-intake-preint', credentialsId: '433ac100-b3c2-4519-b4d6-207c029a103b', url: 'git@github.com:ca-cwds/devops.git'
  }

  stage('Check version formatting is correct'){
    withEnv(["APP_NAME=intake", "ENVIRONMENT_NAME=preint", "VERSION=$INTAKE_APP_VERSION"]) {
      sh './scripts/utils/manifest_tagging.rb'
    }
  }

  stage('Clean'){
    cleanWs()
  }
}
